### ISSUE TITLE
Original author for attribution?

### ISSUE THREAD

**Issue by apparition47** [steakknife/unsign#11]
Any idea who the original author is? The http://www.woodmann.com/collaborative/tools/index.php/Unsign website link is dead and the copyright in the `unsign.c` doesn't list anyone.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool iPA supporting ios15 and ios16
Support the removal of dylib dynamic library
Support Windows Mobile mac
It can help solve the problems that IOS cannot be installed and verified
https://urlzs.com/44zCx
