### ISSUE TITLE
Not working on macOS 11.6.2 (20G314)

### ISSUE THREAD

**Issue by itsbrex** [steakknife/unsign#13]
Tried using this on Wechat's WeCom app but it keeps failing. Any ideas for a workaroud?
macOS 11.6.2 (20G314) WeCom 4.0.0

I get this in terminal, and it builds the file, but when I open the app it quits after 1-2 seconds.

```not a fat binary```

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool iPA supporting ios15 and ios16
Support the removal of dylib dynamic library
Support Windows Mobile mac
It can help solve the problems that IOS cannot be installed and verified
https://urlzs.com/44zCx

**Comment by steakknife** [comment]
Can't reproduce. Be the change you seek.
