### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by phynet** [steakknife/unsign#7]
Hi Barry, I hope you don't mind that I use your code for creating my own formula to install it through homebrew (locally, not going to upload it to global repo). https://github.com/phynet/unsign-xcode
BTW: thanks for this awesome code 😄!

**Comment by steakknife** [comment]
Thanks, but it’s not my code. Homebrew has refused such formulas in the past. I tried to get unsign and makeheaders formulas included to no avail. Feel free to keep trying. 

`brew install {{url to raw formula text}}` is a workaround.

✌️

**Comment by phynet** [comment]
Eh, yes, the idea is to tap it like a local brew. I have no intentions to uploaded to the public homebrew, but since I used your repo to do it I wanted to let you know. 😄

**Comment by steakknife** [comment]
Meh, no worries. I’m just the librarian. :]
