### ISSUE TITLE
Make build broken on Mojave or greater

### ISSUE THREAD

**Issue by jamsinclair** [steakknife/unsign#8]
Just noting down that the current makefile build will break on OSX 10.4 or greater with:
> ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)

To workaround this, update the ARCHS flags in the Makefile to:
```
ARCHS = -arch x86_64
```

**Comment by varenc** [comment]
made PR #9  that addresses this =)

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool iPA supporting ios15 and ios16
Support the removal of dylib dynamic library
Support Windows Mobile mac
It can help solve the problems that IOS cannot be installed and verified
https://urlzs.com/44zCx
